prepare-shakespeare-char:
  main: data/shakespeare_char/prepare
  sourcecode:
    - data/shakespeare_char/prepare.py

train-shakespeare-char:
  main: train  # Intentionally omitting config script - see config
               # flags below
  sourcecode:
    - train.py
    - model.py
    - configurator.py
  flags:
    # Hyperparameters

    batch_size: 64
    beta1: 0.9
    beta2: 0.99
    block_size: 256
    decay_lr: true
    dropout: 0.2
    grad_clip: 1.0
    gradient_accumulation_steps: 1
    init_from:
      default: scratch
      choices: [scratch, resume, gpt2]
    learning_rate: 1e-3
    lr_decay_iters: 5000
    max_iters: 5000
    min_lr: 1e-4
    warmup_iters: 100
    weight_decay: 1e-1

    # Shakespeare config (from config/train_shakespeare_char.py) -
    # these ought not be modified by the user and should be hidden
    # (pending [this
    # feature](https://github.com/guildai/guildai/issues/507) in
    # Guild).

    always_save_checkpoint: False
    dataset: 'shakespeare_char'
    eval_interval: 250
    eval_iters: 200
    log_interval: 10
    n_embd: 384
    n_head: 6
    n_layer: 6

  requires:
    - operation: prepare-shakespeare-char
  output-scalars:
    - 'iter (?P<step>\step): loss (?P<loss>\value).*, mfu (?P<mfu>\value)'
