prepare-shakespeare-char:
  main: data/shakespeare_char/prepare
  sourcecode:
    - data/shakespeare_char/prepare.py

train-shakespeare-char:
  main: train  # Intentionally omitting config script - see config
               # flags below
  sourcecode:
    - train.py
    - model.py
    - configurator.py
  flags:
    # Hyperparameters

    batch_size: 64
    beta1: 0.9
    beta2: 0.99
    block_size: 256
    decay_lr: true
    dropout: 0.2
    grad_clip: 1.0
    gradient_accumulation_steps: 1
    init_from:
      default: scratch
      choices: [scratch, resume, gpt2, gpt2-medium, gpt2-large, gpt2-xl]
    learning_rate: 1e-3
    lr_decay_iters: 5000
    max_iters: 5000
    min_lr: 1e-4
    warmup_iters: 100
    weight_decay: 1e-1

    # System
    device:
      default: cuda
      choices: [cpu, cuda, cuda:0, cuda:1, cuda:2, cuda:3, cuda:4, mps]
      allow-other: true
    dtype:
      default: bfloat16
      choices: [bfloat16, float32, float16]
    compile: true

    # Shakespeare config (from config/train_shakespeare_char.py) -
    # these ought not be modified by the user and should be hidden
    # (pending [this
    # feature](https://github.com/guildai/guildai/issues/507) in
    # Guild).

    always_save_checkpoint: False
    dataset: 'shakespeare_char'
    eval_interval: 250
    eval_iters: 200
    log_interval: 10
    n_embd: 384
    n_head: 6
    n_layer: 6

  requires:
    - operation: prepare-shakespeare-char
      name: prepared-data

  output-scalars:
    - 'iter (?P<step>\step): loss (?P<loss>\value).*, mfu (?P<mfu>\value)'

sample-shakespeare-char:
  main: sample
  sourcecode:
    - sample.py
    - model.py
    - configurator.py

  flags:
    num_samples: 10
    max_new_tokens: 500
    start:
      required: true
    top_k: 200

    # System
    device:
      default: cuda
      choices: [cpu, cuda, cuda:0, cuda:1, cuda:2, cuda:3, cuda:4, mps]
      allow-other: true

  requires:
    - operation: train-.*
      name: trained-model

    - file: data/shakespeare_char/meta.pkl
      target-path: data/shakespeare_char
      name: dataset-meta
